v.1.0 первая поптыка
RifatSuleymanov/java-shareit pull request #1
Opened 2024-01-09 13:03 UTC by RifatSuleymanov

2024-01-10 21:10 UTC, sergeymamonov requested changes

2024-01-10 21:10 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/user/dao/UserDaoImpl.java
> +        if (user.getEmail() != null) {
Условие ифов на строках 33 и 34 можно объединить через &&.

2024-01-10 21:10 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/user/service/UserService.java
> +    public UserService(UserDao userDao) {
Можно не писать конструктор руками, а воспользоваться аннотацией Ломбок.

2024-01-10 21:10 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public UserController(UserService userService) {
Можно не писать конструктор руками.

2024-01-10 21:10 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemController(ItemService itemService) {
Лучше не писать конструктор руками.

2024-01-11 07:07 UTC, RifatSuleymanov commented on src/main/java/ru/practicum/shareit/exception/controller/ErrorController.java
> +        return new ErrorResponse("NOT FOUND", e.getMessage());
+

2024-01-11 07:12 UTC, RifatSuleymanov commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +    public ItemService(ItemDao itemDao, UserDao userDao) {
+

2024-01-11 07:13 UTC, RifatSuleymanov commented on src/main/java/ru/practicum/shareit/user/dao/UserDaoImpl.java
> +        if (user.getEmail() != null) {
+

2024-01-11 07:13 UTC, RifatSuleymanov commented on src/main/java/ru/practicum/shareit/user/service/UserService.java
> +    public UserService(UserDao userDao) {
+

2024-01-11 07:14 UTC, RifatSuleymanov commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public UserController(UserService userService) {
+

2024-01-11 07:15 UTC, RifatSuleymanov commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemController(ItemService itemService) {
+

2024-01-11 07:21 UTC, RifatSuleymanov commented on src/main/java/ru/practicum/shareit/exception/controller/ErrorController.java
> +}
+

2024-01-11 07:21 UTC, RifatSuleymanov commented on src/main/java/ru/practicum/shareit/exception/model/ErrorResponse.java
> +    public ErrorResponse(String error, String description){
+

2024-01-11 07:22 UTC, RifatSuleymanov commented on src/main/java/ru/practicum/shareit/exception/BadRequest.java
> +public class BadRequest extends IllegalArgumentException {
+

2024-01-11 07:22 UTC, RifatSuleymanov commented on src/main/java/ru/practicum/shareit/exception/Conflict.java
> +public class Conflict extends IllegalArgumentException {
+

2024-01-11 07:22 UTC, RifatSuleymanov commented on src/main/java/ru/practicum/shareit/exception/NotFoundException.java
> +public class NotFoundException extends IllegalArgumentException {
+

2024-01-11 07:23 UTC, RifatSuleymanov commented on src/main/java/ru/practicum/shareit/item/dao/ItemDaoImpl.java
> +            throw new NotFoundException("Вы не можете редактировать чужие объявления");
+

2024-01-11 07:23 UTC, RifatSuleymanov commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +    public ItemService(ItemDao itemDao, UserDao userDao) {
+

2024-01-11 08:16 UTC, closed without merging