v1.0 добавлено база данных, Реализовано функции бронирования, реализо…
RifatSuleymanov/java-shareit pull request #4
Opened 2024-01-17 11:03 UTC by RifatSuleymanov

…вано добавление отзывоа

2024-01-18 20:18 UTC, sergeymamonov requested changes

2024-01-18 20:18 UTC, sergeymamonov commented on src/main/resources/schema.sql
> +    description  varchar NOT NULL,
Размер varchar должен быть ограничен. Проверьте все varchar в схеме.

2024-01-23 07:12 UTC, RifatSuleymanov commented on src/main/resources/schema.sql
> +    description  varchar NOT NULL,
+

2024-01-23 07:12 UTC, RifatSuleymanov commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +@Data
+

2024-01-24 10:05 UTC, sergeymamonov approved these changes

2024-01-24 10:05 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +@Setter
Dto - это неизменяемый класс. То есть его создали с какими-то значениями. И больше он не меняется. Следовательно, у такого класса не может быть сеттеров. Полям лучше добавить модификатор final. И для класса лучше добавить модификатор final, чтобы у класса не возможно было создать наследников. Касается все классов dto.

2024-01-27 15:11 UTC, merged