ТЗ 15 версия 1. Добавил новый функционал и тесты
RifatSuleymanov/java-shareit pull request #5
Opened 2024-01-30 08:12 UTC by RifatSuleymanov

2024-01-30 18:08 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
>                  .map(this::setDtoComments)
Здесь выполняются запросы к БД в цикле. Так делать не нужно, так как это грузит БД и долго выполняется.
Аналогично и в следующей строке .map(this::setDtoNextAndLast). Плюс на вызове метода setDtoNextAndLast не сработает аннотация Transactional, так как вызов происходит из того же самого класса, где размещен метод.

2024-01-30 18:13 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/request/service/RequestService.java
> +        listDto.forEach(this::setRequestItems);
Запросы к БД в цикле.

2024-01-30 18:14 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/request/service/RequestService.java
> +        listDto.forEach(this::setRequestItems);
Запросы к БД в цикле.

2024-01-30 18:27 UTC, sergeymamonov commented on src/test/java/ru/practicum/shareit/bookingTest/BookingRepositoryTest.java
> +        User user1 = new User();
Если пользователи одинаковые, в разных теста, то можно вынести создание пользователей в метод, аннотированный @BeforeEach. Или хотя бы вынести в отдельный метод создание пользователей, чтобы не повторять этот код в каждом тесте.

2024-01-30 18:42 UTC, RifatSuleymanov commented on src/main/java/ru/practicum/shareit/exception/controller/ErrorController.java
+

2024-01-30 19:11 UTC, RifatSuleymanov commented on src/test/java/ru/practicum/shareit/bookingTest/BookingRepositoryTest.java
> +        User user1 = new User();
+

2024-01-30 19:11 UTC, RifatSuleymanov commented on src/main/java/ru/practicum/shareit/booking/services/BookingService.java
> +        if (from < 0) {
+

2024-01-30 20:18 UTC, RifatSuleymanov commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
>                  .map(this::setDtoComments)
+

2024-01-30 20:35 UTC, RifatSuleymanov commented on src/main/java/ru/practicum/shareit/booking/services/BookingService.java
> +        if (from < 0) {
У меня почему то если проверку меньше 0 убрать тест в постмане не проходит, поэтому я в контроллере убрал аннотацию @PositiveOrZero

2024-01-30 20:45 UTC, RifatSuleymanov commented
> ErrorResponse - пропущены модификаторы доступа для полей.
> 
> Рекомендовал бы попрактиковать параметризированные тесты https://reflectoring.io/tutorial-junit5-parameterized-tests/
> 
> Располагать вместе интерфейс и реализацию - это не есть хорошо. Например, это может говорить о неверной архитектуре.

cпасибо за ссылку, обязательно изучу, хотя с английским у меня отношение не очень

2024-01-30 20:51 UTC, RifatSuleymanov commented on src/main/java/ru/practicum/shareit/request/service/RequestService.java
> +        listDto.forEach(this::setRequestItems);
+

2024-01-30 20:51 UTC, RifatSuleymanov commented on src/main/java/ru/practicum/shareit/request/service/RequestService.java
> +        listDto.forEach(this::setRequestItems);
+

2024-02-01 04:38 UTC, sergeymamonov commented
Располагать вместе интерфейс и реализацию - это не есть хорошо. Например, это может говорить о неверной архитектуре. - Вынести один из классов в подпакет - это не решение, тут речь про то, чтобы класс реализация и интерфейс лежали в разных пакетах, например один в пакете с доменными (бизнес сущностями), а другой в пакете с реализацией.

2024-02-01 04:43 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
>      public ItemDto setDtoNextAndLast(ItemDto dto) {
Метод вызывается только в этом классе, значит должен быть приватным.

2024-02-01 04:43 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
>                  .map(this::setDtoNextAndLast)
Запросы в цикле к БД остались.

2024-02-01 04:43 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/request/service/RequestService.java
> +        listDto.forEach(this::setRequestItems);
Запросы в цикле остались.

2024-02-01 04:44 UTC, sergeymamonov commented
Обратите внимание, если метод вызывается только в этом же классе, то его лучше сделать приватным. Пример, ru.practicum.shareit.request.service.RequestService#setRequestItems

2024-02-01 06:02 UTC, RifatSuleymanov commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
>      public ItemDto setDtoNextAndLast(ItemDto dto) {
+

2024-02-01 15:52 UTC, RifatSuleymanov commented on src/main/java/ru/practicum/shareit/request/service/RequestService.java
> +        listDto.forEach(this::setRequestItems);
Надеюсь все правильно сделал

2024-02-01 15:52 UTC, RifatSuleymanov commented on src/main/java/ru/practicum/shareit/request/service/RequestService.java
> +        listDto.forEach(this::setRequestItems);
Надеюсь все правильно сделал

2024-02-01 15:52 UTC, RifatSuleymanov commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
>                  .map(this::setDtoNextAndLast)
Надеюсь все правильно сделал, сам уже запутался вроде тесты проходит

2024-02-02 04:15 UTC, sergeymamonov requested changes
Про пакеты: про интерфейс и реализацию, мое мнение, что если вам не требуется разносить по модулям их, если у вас получается так, что они лежат вместе, то значит в данном случае создавать интерфейс отдельно излишне. Мы только усложняем этим наш код.
Создавать пакеты business и businessInterface не нужно. Так не делают)

И не забывайте, пакеты пишутся в snake_case.

2024-02-02 04:15 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/business/item/service/ItemService.java
> +        for (ItemDto itemDto : itemDtoList) {
На этой строке вы начинаете цикл, а на следующей строке и строках 97, 104, делаете запросы к БД. Получаются запросы к БД в цикле.

2024-02-02 04:15 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/business/item/service/ItemService.java
> +    private final ItemRepository itemRepository;
А почему у вас заинджекчено две сущности для получения данных и ItemDao и ItemRepository?

2024-02-02 13:05 UTC, RifatSuleymanov commented on src/main/java/ru/practicum/shareit/business/item/service/ItemService.java
> +    private final ItemRepository itemRepository;
исправил

2024-02-02 13:06 UTC, RifatSuleymanov commented on src/main/java/ru/practicum/shareit/business/item/service/ItemService.java
> +        for (ItemDto itemDto : itemDtoList) {
вроде исправил, пришлось переписать метод и очень много думать

2024-02-02 13:07 UTC, RifatSuleymanov commented
> Про пакеты: про интерфейс и реализацию, мое мнение, что если вам не требуется разносить по модулям их, если у вас получается так, что они лежат вместе, то значит в данном случае создавать интерфейс отдельно излишне. Мы только усложняем этим наш код. Создавать пакеты business и businessInterface не нужно. Так не делают)
> 
> И не забывайте, пакеты пишутся в snake_case.
Я пока не смог найти информацию и прочитать про данную структуру(времени не очень хватает)  в будущем исправлюсь

2024-02-03 13:32 UTC, sergeymamonov approved these changes

2024-02-03 13:32 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +    private final BookingRepository bookingRepository;
Аналогично, два дублирующих бина bookingDao и bookingRepository.

2024-02-03 13:32 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/dao/impl/ItemDaoImpl.java
> +            items.addAll(itemRepository.findAllByRequestId(requestId));
Запросы к БД в цикле.

2024-02-05 12:34 UTC, merged