Add docker
RifatSuleymanov/java-shareit pull request #8
Opened 2024-02-07 08:16 UTC by RifatSuleymanov

2024-02-08 19:18 UTC, sergeymamonov requested changes
Давайте именам более осмысленное название.
В основном сервисе не должно быть проверок входных данных. Все эти проверки должны быть венесены в gateway. Пример, BookingService строка 72 проверка from < 0 - это избыточная проверка.
Основной сервис BadRequestException - проверьте все места, где выбрасывается это исключение. Валидацию входных данных нужно перенести в gateway.
UnknownStateException - аналогично.

Я бы не делал столько абстраций...Dao, DaoImpl и ...Repository. Для такого проекта один интерфейс и реализация - это максимум.

RequestService setRequestItems - если метод вызывается только внутри класса, то он должен быть приватный.

Тесты на проверку валидации входных параметров в основном сервисе не будут проходить. Их можно вынести в тесты в сервисе gateway.

2024-02-08 19:18 UTC, sergeymamonov commented on server/src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +        itemDtoList.forEach(itemDto -> itemDto.setNextBooking(nextBookings.get(itemDto.getId())));
Запросы к БД в цикле.

2024-02-08 19:18 UTC, sergeymamonov commented on server/src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +        itemDtoList.forEach(itemDto -> itemDto.setLastBooking(lastBookings.get(itemDto.getId())));
Запросы к БД в цикле.

2024-02-08 19:42 UTC, RifatSuleymanov commented on server/src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +        itemDtoList.forEach(itemDto -> itemDto.setLastBooking(lastBookings.get(itemDto.getId())));
+

2024-02-08 19:43 UTC, RifatSuleymanov commented on gateway/src/main/java/ru/practicum/shareit/exceptions/NotFoundException.java
> +public class NotFoundException extends RuntimeException {
+

2024-02-08 19:47 UTC, RifatSuleymanov commented on gateway/src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> + * TODO Sprint add-controllers.
+

2024-02-11 05:35 UTC, sergeymamonov approved these changes
В предыдущем ревью пропустил слово в замечании)
Давайте именам **коммитов** более осмысленное название.

ItemController - аннотации @PositiveOrZero, @Positive стр. 42, 43 можно удалить.

Выполните глобальный поиск по пакету service (основной сервиса) выражения from < 0. Этих проверок в основном сервисе быть не должно.

BadRequestException - это слишком общее название ошибки. Я бы лучше сделал несколько ошибок для каждого конкретного случая. И ошибки с более специфическими названиями.

2024-02-12 10:52 UTC, merged